import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest : '/manifest.json',
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>  
        <meta name="color-scheme" content="light only" />
        <meta name="theme-color" content="#333333"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
